config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'home'               => "home#index"

  post '/new_comment'      => "comments#new_comment"

  delete '/comments/:id'   => "comments#delete_comment"

  get '/comments/:id/edit' => "comments#edit"


  devise_for :users
  resources :topics


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :topic

  validates :content, :topic, :user, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user

  has_many :comments, :dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :topics
 has_many :comments

 validates :username, :favorite_weapon, :splatoon_game, :timezone, :voice_chat, :language, :friend_code,
           presence: true, length: {minimum: 1}

 validates_inclusion_of :voice_chat, :in =>[true, false]

 validates_uniqueness_of :email, :username, :friend_code

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    home_path
  end

  def after_sign_in_path_for(resource)
    home_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys:
      [:email, :current_password, :location, :username, :splatoon_game, :favorite_weapon, :timezone, :language
      ])
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def edit
  end

  def new_comment
    @new_comment = Comment.new(add_comment)
    if @new_comment.save
      redirect_to topic_path(params[:topic_id])
    else
      flash[:alert] = "Something wrong happened...."
    end
  end

  def delete_comment
    @delete_comment = Comment.find(params[:id]).delete
    flash[:notice] = "Comment Deleted"
    redirect_to home_path
  end

  private

  def add_comment
    params.require(:comment).permit(:content, :topic_id, :user_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!

  def index
    @user    = current_user
    @topics  = Topic.joins(:user)
               .select("topics.id AS topics_id, topics.title AS topics_title, topics.subject AS topics_subject, topics.content AS topics_content, users.email AS users_email")
               .order(created_at: :desc)
               .limit(10)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!


  def index
  end

  def show
    @topic = Topic.find(params[:id])
    @comments = Comment.where(topic_id: params[:id])
                .order(created_at: :desc)
                .limit(10)
  end

  def new
    @user = current_user
  end

  def update
    @update_topic = Topic.find(params[:id])
    if @update_topic.update(update_topic)
      redirect_to home_path
      flash[:notice] = "Topic Updated!"
    else
      redirect_to :back, flash[:alert] = "There was a problem updating the topic!"
    end
  end

  def create
    @new_topic = Topic.new(new_topic)
    if @new_topic.save
      redirect_to home_path
      flash[:notice] = "New topic created!"
    else
      redirect_to :back
    end
  end

  def edit
    @edit_topic = Topic.find(params[:id])
    redirect_to home_path, alert: "You do not have access to view this page!" unless current_user.id == @edit_topic.user_id
  end

  def destroy
    Topic.find(params[:id]).destroy
    redirect_to home_path, notice: "Topic Deleted!"
  end


  private

    def new_topic
      params.require(:topic).permit(:title, :subject, :content, :user_id)
    end

    def update_topic
      params.require(:topic_u).permit(:topic_id, :title, :subject, :content)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def user_username(user)
    user.username if user && user.username.present?
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/edit.html.erb
<div class="row mt-5">
<div class="col-8 offset-1">
  <h2>Edit your comment:</h2>
  <form>
  <textarea class="form-control"></textarea>
  <button type="submit" class="btn btn-primary mt-3">Update</button>
  </form>
</div>
</div>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/home/index.html.erb
<div class="row">
    <div class="col-3 mt-5 ml-5">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"></h5>
          <h6 class="card-subtitle mb-2 text-muted">Hello, <%= user_username(@user) %></h6>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>
    </div>
    <div class="col-6 mt-5 offset-1">
      <h2>Recent Topics</h2>
      <ul class="list-group">
        <% @topics.each do |topic| %>
  <li class="list-group-item"><%= topic.topics_title %> by <%= topic.users_email%> <a href="/topics/<%=topic.topics_id %>">view </a>
        <% end %>
</ul>
    </div>
</div>


<h2>dev</h2>

add friend code
switch/wii u

do u want ur code public?

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SplatoonLife</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="<%= root_path %>">Splatoon Life</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if user_signed_in? %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="<%= home_path %>">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="<%= topics_path %>">Topics</a>
        </li>
        <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile Settings
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= edit_user_registration_path %>">Edit Profile</a>
        </div>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="<%= destroy_user_session_path %>" data-method="delete">Sign Out</a>
      </li>
      </ul>
    </div>
    <% end %>
  </nav>

    <%= yield %>
  </body>
</html>

app/views/topics/edit.html.erb
<div class="row">
<div class="col-6 offset-1">
  <form action="/topics/<%= @edit_topic.id %>" method="post">
  <input name="_method" type="hidden" value="patch" />
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  Title: <input type="text" name="topic_u[title]" class="form-control" value="<%= @edit_topic.title %>"> <br />
  Subject: <input type="text" name="topic_u[subject]" class="form-control" value="<%= @edit_topic.subject %>"><br />
  Content: <textarea name="topic_u[content]" class="form-control"><%= @edit_topic.content %></textarea><br />
<button class="btn btn-primary" type="submit">Update Topic</button>
</form>
<a href="/topics/<%= @edit_topic.id %>">Back</a>
</div>
</div>

app/views/topics/index.html.erb
<h1>Topics#inde</h1>
<p>Find me in app/views/topics/inde.html.erb</p>

app/views/topics/new.html.erb
  <div class="row">
    <div class="col-5 offset-1 mt-5">
      <form action="/topics" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      Title: <input type="text" name="topic[title]" class="form-control"> <br />
      Subject: <input type="text" name="topic[subject]" class="form-control" placeholder="ex: Let's Battle! or I need advice on chargers and gear equips!"><br />
      Content: <textarea name="topic[content]" class="form-control"></textarea><br />
      <input type="hidden" name="topic[user_id]" value="<%= @user.id %>">
    <button class="btn btn-primary" type="submit">Create Topic</button>
    </form>
    </div>
</div>

app/views/topics/show.html.erb
<div class="row">
  <div class="col-10">

    <div class="card text-center offset-1 mt-5">
      <div class="card-header">
        <%= @topic.title %>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= @topic.subject %></h5>
        <p class="card-text"><%= @topic.content %></p>
          <footer class="blockquote-footer mb-4">Topic made by: <cite title="Source Title"><%= @topic.user.email %></cite> on <%= @topic.created_at %></footer>
      </div>
      <div class="card-footer text-muted">
        <% if current_user.id == @topic.user.id %>
          <%= link_to '<button type="button" class="btn btn-primary">Edit My Topic</button>'.html_safe, edit_topic_path(@topic.id) %>
        <%= link_to '<button type="button" class="btn btn-danger">Delete My Topic</button>'.html_safe, "/topics/#{@topic.id}",
         :data => {:confirm => 'Do you really want to delete?'}, method: :delete %>
        <% end %>
      </div>
    </div>

</div>
</div>
</div>
<div class="row">
<div class="col-9 offset-1">
<h2 class=" mt-5">Comments (<%= @comments.count%>)</h2>
  <form action="/new_comment" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <textarea name="comment[content]" class="form-control mt-4"></textarea>
    <input type="hidden" name="comment[topic_id]" value="<%= @topic.id %>">
    <input type="hidden" name="comment[user_id]" value="<%= current_user.id %>">
    <input type="hidden" name="topic_id" value="<%= @topic.id %>">
    <button type="submit" class="btn btn-info mt-4">Add Comment</button>
  </form>
</div>
</div>
<div class="row">
  <div class="col-8 offset-1 mt-5">
    <ul class="list-group">
      <% @comments.each do |comment| %>
        <li class="list-group-item"><%= comment.content %>
          <% if current_user.id = comment.user_id %>
          <%= link_to "Edit Comment", "/comments/#{comment.id}/edit" %> |
          <%= link_to "Delete Comment", "/comments/#{comment.id}", data: { confirm: "Are you sure?"}, method: :delete %>
          <% end %>
        </li>
      <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<h1 class="text-center">Splatoon Life</h1>

<div class="row mt-5">
    <div class="col-6">

      <%= image_tag("welcome.gif", :alt => "welcome") %>

    </div>

    <div class="col-6">

      <h5>A place to make and chat with friends around the world for Splatoon.</h5>
      <%= link_to "Login", new_user_session_path %> <br />
      <%= link_to "Register", user_session_path %><br />
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    </div>
</div>